modLoader="javafml"
loaderVersion="x.x.x"
license="MIT"

[[mods]]
modId="kamen_rider_boss_you_and_me"
logoFile="kamen_rider_boss_you_and_me.png"
version="0.2.7alpha-3"
displayName="KamenRiderBossYOUandME"
displayURL="https://space.bilibili.com/1410016591"
authors="xiaoshi2022,xiaohaoxiaohao(Partial models),qileixi02(Art designer)"
description='''
This is a mod based on the Kamen Rider series, bringing various Boss and monster into your game mc...
'''

[[dependencies.kamen_rider_boss_you_and_me]]
modId="forge"
mandatory=true
versionRange="[47.0.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.kamen_rider_boss_you_and_me]]
modId="geckolib"
mandatory=true
versionRange="[4.2.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.kamen_rider_boss_you_and_me]]
modId="minecraft"
mandatory=true
versionRange="1.20.1"
ordering="NONE"
side="BOTH"

[[dependencies.kamen_rider_boss_you_and_me]]
modId="curios"
mandatory=true
versionRange="[1.20.1-5.4.4.0,)"
ordering="NONE"
side="BOTH"